name: Code quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "*"

jobs:
  next-lint:
    name: Run next lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run next lint
        run: bun run lint

  typescript-check:
    name: Run typescript check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run typescript check
        run: bun run typecheck
