name: Deployments

on:
  push:
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "*"

jobs:
  call-workflow-passing-data:
    uses: Rutger505-Org/kubernetes-infrastructure/.github/workflows/deployments.yaml@main
    secrets: inherit
