name: Deployments

on:
  push:
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: next-template
  DOCKER_IMAGE: rutger505/next-template

jobs:
  build-docker-image:
    if: github.event.action != 'closed'
    name: Build Docker image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.config.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate build config
        id: config
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi

          echo "Setting tag to $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.config.outputs.tag }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache,mode=max

  deploy-to-kubernetes:
    if: github.event.action != 'closed'
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs:
      - build-docker-image

    strategy:
      matrix:
        environment:
          - ${{ startsWith(github.ref, 'refs/tags/') && 'production' || format('pr-{0}', github.event.pull_request.number) }}

    environment:
      name: ${{ matrix.environment }}
      url: https://${{ steps.config.outputs.ingress_host }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate deployment config
        id: config
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            INGRESS_HOST=${{ vars.BASE_DOMAIN }}
            LETSENCRYPT_ENV="production"
          else
            INGRESS_HOST=${{ github.sha }}.${{ vars.BASE_DOMAIN }}
            LETSENCRYPT_ENV="staging"
          fi

          echo "Setting ingress host to $INGRESS_HOST"
          echo "ingress_host=$INGRESS_HOST" >> $GITHUB_OUTPUT

          echo "Setting letsencrypt_env to $LETSENCRYPT_ENV"
          echo "letsencrypt_env=$LETSENCRYPT_ENV" >> $GITHUB_OUTPUT

          NAMESPACE=$APP_NAME-${{ matrix.environment }}
          echo "Setting namespace to $NAMESPACE"
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT

      - name: Setup Kubernetes
        uses: ./.github/actions/setup-k8s
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: OpenTofu Apply
        working-directory: ./deploy
        env:
          TF_VAR_image: ${{ env.DOCKER_IMAGE }}:${{ needs.build-docker-image.outputs.tag }}
          TF_VAR_hostname: ${{ steps.config.outputs.ingress_host }}
          TF_VAR_certificate_issuer: ${{ steps.config.outputs.letsencrypt_env }}
        run: |
          tofu init
          tofu plan -out=tfplan -input=false 
          tofu apply -var-file="0-values" -input=false -auto-approve tfplan

  cleanup-environment:
    if: github.event.action == 'closed'
    name: Delete PR Environment
    runs-on: ubuntu-latest
    environment:
      name: pr-${{ github.event.pull_request.number }}

    steps:
      - name: Generate cleanup config
        id: config
        run: |
          ENVIRONMENT=pr-${{ github.event.pull_request.number }}
          NAMESPACE=${{ env.APP_NAME }}-$ENVIRONMENT

          echo "Setting environment to $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

          echo "Setting namespace to $NAMESPACE"
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT

      - name: Safety check
        run: |
          NAMESPACE=${{ steps.config.outputs.namespace }}

          if [[ "$NAMESPACE" == *"production"* ]]; then
            echo "❌ Refusing to delete namespace containing 'production'"
            exit 1
          fi

          if [[ "$NAMESPACE" != ${{ env.APP_NAME }}-pr-* ]]; then
            echo "❌ Namespace doesn't match expected pattern for PR environments"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Kubernetes
        uses: ./.github/actions/setup-k8s
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: OpenTofu Destroy
        working-directory: ./deploy
        run: |
          tofu init
          tofu plan -destroy -out=tfplan -input=false 
          tofu apply -var-file="1-dummy-values" -var-file="0-values" -input=false -auto-approve tfplan
